#!/bin/bash
sudo dnf update -y
sudo dnf install -y httpd php php-mysqlnd php-fpm php-json php-xml php-mbstring mariadb105 git

sudo systemctl start httpd
sudo systemctl enable httpd

cd /var/www/html/
# Github
git clone https://github.com/tu_usuario/tu_repositorio.git banco_app

# Permisos
sudo usermod -a -G apache ec2-user
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www
find /var/www -type d -exec sudo chmod 2775 {} \;
find /var/www -type f -exec sudo chmod 0664 {} \;

# Zona horaria
sudo timedatectl set-timezone Europe/Madrid

# Página
echo '<?php phpinfo(); ?>' > /var/www/html/banco_app/info.php
echo '<h1>¡Hola desde mi aplicación bancaria en AWS!</h1>' > /var/www/html/banco_app/index.html

echo "Servidor web Apache con PHP y aplicación descargada desde Git."
echo "***********************************************************************"
